language: php

php:
  - 5.3

before_script:
  - export DISPLAY=:99
  - mkdir -p /tmp/plugins/lsgallery
  - mv * /tmp/plugins/lsgallery
  - mkdir /tmp/ls && git clone git://github.com/stfalcon-studio/livestreet.git /tmp/ls
  - cp -a /tmp/ls/* ./
  - cp /tmp/ls/.htaccess ./
  - mkdir -p plugins/lsgallery && cp -a /tmp/plugins/lsgallery/* plugins/lsgallery
  - mkdir -p ./uploads/images/lsgallery
  - echo "lsgallery" > ./plugins/plugins.dat
  - git clone git://github.com/stfalcon-studio/ls-plugin_sitemap.git ./plugins/sitemap
  - echo "sitemap" >> ./plugins/plugins.dat

  # change application working folders for write access
  - chmod -R 0777 ./tmp
  - chmod -R 0777 ./uploads
  - chmod -R 0777 ./templates/cache/
  - chmod -R 0777 ./templates/compiled/

  # install required PHP stuff
  - sudo apt-get update
  - sudo apt-get install php5 php5-cli php5-mysql php5-mcrypt php5-xsl php5-xdebug php-apc php5-gd php5-curl php5-intl php5-xmlrpc

  # launch apache, MySQL and PHPUnit Selenium installers
  - ./tests/travis/apache_setup.sh
  - ./tests/travis/mysql_setup.sh
  - mysql -u root -B social_test < ./plugins/lsgallery/activate.sql
  - mysql -u root -B social_test < ./plugins/lsgallery/tests.sql
  - mysql -u root -e "USE social_test; SHOW TABLES;" | wc -l
  - cp ./config/config.test.php.dist config/config.test.php
  - cp ./config/config.test.php.dist config/config.local.php
  - sudo sed -i s/sql-mode/#sql-mode/ /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql restart
  - sleep 5

  - rm -rf ./install
  - wget -S http://livestreet.test/ -O /dev/null

  # start virtual display
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # download and launch Selenium
  - wget -O /tmp/selenium-server-standalone.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar /tmp/selenium-server-standalone.jar > /dev/null &
  - sleep 5


script: HTTP_APP_ENV=test cd tests/behat/ && php behat.phar --config='../../plugins/lsgallery/tests/behat/behat.yml' --strict
